### ISSUE TITLE
In console interface: Link player numbers with player colours

### ISSUE THREAD

**Issue by mapto** [mapto/4oBe4e#20]
Currently in the board console visualisation players are indicated by colour. In the console input, however, players are prompted their moves by number. Users can't relate one to the other. We need to fix this.

Please propose solution ideas before we engage in implementation.

**Comment by vkantsev** [comment]
Let's colour the prompt per player?

**Comment by luchesar** [comment]
Do we have a list of the players anywhere in the console view?

Along with the proposition of `vkantsev` we can have a numbered list of the players:
1. Petkan Prokopiev on Red background
2. John Smith on Blue backgound
3. Han Krum on Yellow backgound
4. Zapryan Zapryanov on Green background
